#!/bin/bash
# health-monitor.sh — Cross-repository health monitoring for SwiftAnvil
# Runs swiftanvil health scan across all sibling repos and generates aggregated report

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
META_DIR="$WORKSPACE_DIR/swiftanvil-meta"
REPORT_PATH="$META_DIR/HEALTH_DASHBOARD.md"
JSON_REPORT_PATH="$META_DIR/health-data.json"

SWIFTANVIL_BIN="${SWIFTANVIL_BIN:-swiftanvil}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "🔍 SwiftAnvil Cross-Repo Health Monitor"
echo "========================================"
echo "Workspace: $WORKSPACE_DIR"
echo ""

# Find all repos with Package.swift
repos=()
for dir in "$WORKSPACE_DIR"/swiftanvil-*; do
    if [ -d "$dir" ] && [ -f "$dir/Package.swift" ]; then
        repos+=("$dir")
    fi
done

if [ ${#repos[@]} -eq 0 ]; then
    echo "⚠️ No Swift package repos found in $WORKSPACE_DIR"
    exit 0
fi

echo "Found ${#repos[@]} repos to scan:"
for repo in "${repos[@]}"; do
    echo "  - $(basename "$repo")"
done
echo ""

# Run health scan in each repo
health_files=()
for repo in "${repos[@]}"; do
    repo_name=$(basename "$repo")
    echo "🔎 Scanning $repo_name..."

    health_file="$repo/.swiftanvil-health.json"

    if ! command -v "$SWIFTANVIL_BIN" &>/dev/null; then
        echo "  ⚠️ swiftanvil not found, skipping"
        continue
    fi

    if (cd "$repo" && "$SWIFTANVIL_BIN" health scan --quick --format json --output "$health_file" 2>/dev/null); then
        health_files+=("$health_file")
        echo "  ✅ Health data written to $health_file"
    else
        echo "  ❌ Health scan failed"
    fi
done

echo ""
echo "📊 Generating aggregated report..."

# Generate markdown report
cat > "$REPORT_PATH" << 'HEADER'
# SwiftAnvil Health Dashboard

> Auto-generated by `scripts/health-monitor.sh`. Do not edit manually.
> This file is machine-readable: agents parse the JSON table to detect drift.

HEADER

# Add timestamp
printf "**Last Updated:** %s\n\n" "$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$REPORT_PATH"

# Summary table
echo "| Repo | Overall | Tests | Format | Lint | Build Audit | Logging | Network |" >> "$REPORT_PATH"
echo "|------|---------|-------|--------|------|-------------|---------|---------|" >> "$REPORT_PATH"

# JSON array for machine consumption
json_entries=()

for health_file in "${health_files[@]}"; do
    repo_name=$(basename "$(dirname "$health_file")")

    if [ ! -f "$health_file" ]; then
        continue
    fi

    # Parse JSON using Python for reliability
    if ! python3 -c "import json" 2>/dev/null; then
        echo "  ⚠️ Python3 not available, skipping JSON parse"
        continue
    fi

    overall=$(python3 -c "
import json, sys
try:
    data = json.load(open('$health_file'))
    print(data.get('overall', 'unknown'))
except:
    print('unknown')
" 2>/dev/null || echo "unknown")

    # Get individual dimension statuses
    get_dim() {
        python3 -c "
import json, sys
try:
    data = json.load(open('$health_file'))
    for d in data.get('dimensions', []):
        if d['name'] == '$1':
            print(d['status'])
            sys.exit(0)
    print('-')
except:
    print('-')
" 2>/dev/null || echo "-"
    }

    tests=$(get_dim "tests")
    format=$(get_dim "format")
    lint=$(get_dim "lint")
    build_audit=$(get_dim "build-audit")
    logging=$(get_dim "logging")
    network=$(get_dim "network")

    # Color-code overall
    overall_emoji="⚪"
    if [ "$overall" = "pass" ]; then overall_emoji="🟢"; fi
    if [ "$overall" = "warn" ]; then overall_emoji="🟡"; fi
    if [ "$overall" = "fail" ]; then overall_emoji="🔴"; fi

    echo "| $repo_name | $overall_emoji $overall | $tests | $format | $lint | $build_audit | $logging | $network |" >> "$REPORT_PATH"

    # Build JSON entry
    json_entries+=("$(python3 -c "
import json
data = json.load(open('$health_file'))
data['repoPath'] = '$repo_name'
print(json.dumps(data))
" 2>/dev/null || echo "{}")")
done

echo "" >> "$REPORT_PATH"
echo "## Legend" >> "$REPORT_PATH"
echo "" >> "$REPORT_PATH"
echo "- 🟢 pass — All checks passed" >> "$REPORT_PATH"
echo "- 🟡 warn — Non-blocking issues detected" >> "$REPORT_PATH"
echo "- 🔴 fail — Blocking issues require attention" >> "$REPORT_PATH"
echo "- ⚪ unknown — Could not determine status" >> "$REPORT_PATH"
echo "" >> "$REPORT_PATH"
echo "## Agent Consumption" >> "$REPORT_PATH"
echo "" >> "$REPORT_PATH"
echo "Agents should read \`health-data.json\` for structured data." >> "$REPORT_PATH"
echo "The JSON array contains one entry per repo with full dimension breakdowns." >> "$REPORT_PATH"

# Write JSON array
python3 -c "
import json, sys
entries = []
for entry_str in ${json_entries[@]+\"${json_entries[@]}\"}:
    try:
        entries.append(json.loads(entry_str))
    except:
        pass
with open('$JSON_REPORT_PATH', 'w') as f:
    json.dump(entries, f, indent=2)
" 2>/dev/null || echo "[]" > "$JSON_REPORT_PATH"

echo ""
echo "✅ Reports generated:"
echo "  Markdown: $REPORT_PATH"
echo "  JSON:     $JSON_REPORT_PATH"
echo ""

# Summary
pass_count=$(grep -c "🟢 pass" "$REPORT_PATH" 2>/dev/null || echo 0)
warn_count=$(grep -c "🟡 warn" "$REPORT_PATH" 2>/dev/null || echo 0)
fail_count=$(grep -c "🔴 fail" "$REPORT_PATH" 2>/dev/null || echo 0)

echo "Summary: $pass_count pass, $warn_count warn, $fail_count fail"

if [ "$fail_count" -gt 0 ]; then
    echo ""
    echo "${RED}⚠️ $fail_count repo(s) have failing health checks${NC}"
    exit 1
fi

echo ""
echo "${GREEN}✅ All repos healthy${NC}"
